# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - trigger: ":date"
    label: "Date: current date time in various formats"
    replace: "{{"{{date_output}}"}}"
    vars:
      - name: format
        type: choice
        params:
          values:
            - label: Date (2015-10-21)
              id: "%F"
            - label: Datetime (2015-10-21T16:29:42)
              id: "%Y-%m-%dT%H:%M:%S"
            - label: Datetime with fraction of a second (2015-10-21T16:29:42.1337)
              id: "%Y-%m-%dT%H:%M:%S.%f"
            - label: Datetime with fraction of a second and TZ (2015-10-21T16:29:42.1337+01:00)
              id: "%+"
      - name: date_output
        type: date
        params:
          format: "{{"{{format}}"}}"

  - trigger: ":date"
    label: "Date: fixed date `2015-10-21T16:29:42.1337` (for unit tests or code examples)"
    replace: 2015-10-21T16:29:42.1337

  - triggers: [":ip", ":myip", ":wimi"]
    label: Public IP address
    replace: "{{ "{{ipaddr}}" }}"
    vars:
      - name: ipaddr
        type: shell
        params:
          cmd: "curl 'https://api.ipify.org'"