[misc]
{{ "# documentation can be found here: https://github.com/topgrade-rs/topgrade/blob/master/config.example.toml" }}

disable = ["gem", "tlmgr", "vagrant"]

no_retry = true

no_self_update = true

[windows]
self_rename = true
