name: CI

on: push

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - shell: powershell
        run: Invoke-Expression "&{$(Invoke-RestMethod 'https://install.dotfiles.ploki.fr')} -BranchName ${{ github.ref_name }}"

  macos:
    runs-on: macos-latest
    steps:
      - run: sh -c "$(curl -fsLS https://get.chezmoi.io)" -- -b $TMPDIR init --apply --verbose --branch ${{ github.ref_name }} ${{ github.repository_owner }}
