name: CI

on: push

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - shell: powershell
        run: Invoke-RestMethod -Uri https://install.dotfiles.ploki.fr | Invoke-Expression

  macos:
    runs-on: macos-latest
    steps:
      - run: sh -c "$(curl -fsLS https://get.chezmoi.io)" -- -b $TMPDIR init --apply --verbose --branch ci-macos nagromc
