name: CI

on:
  push:
    branches: [ github-actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install-dotfiles:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: brew --version
